name: Build-Test-Analysis

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test-analysis.yml@main
    permissions: write-all
    with:
      solution-name: 'Barly.sln'
